version: "3"

services:
  ssr:
    build: .
    container_name: domain-node-js
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
      - /app/static
    ports:
      - 5000:5000

  tests:
    build: .
    container_name: tests-suite
    command: npm run test
    volumes:
      - .:/app
      - /app/node_modules
      - /app/coverage
